@startuml
title アクティビティサンプル

start 
if(カードを挿入)
    if(暗証番号を入力) then (成功)
        if(入金) then (はい)
        elseif(出金) then (はい)
        endif
    else
        :エラーメッセージ;
    endif
elseif(通帳を挿入)
    :印字;
endif

:記録;
stop

@enduml