@startuml

title ATMサンプル

class 口座 {
口座番号
残高
暗証番号照合()
出金()
入金()
利息加算()
}

class 顧客 {
氏名
個人情報
}

class 取引履歴 {
日時
内容
金額
記録()
}

class カード {
番号
暗証番号
}

class カレンダー{
    カレンダー情報
    日数計算()
    営業日判定()
}

class 通帳{
    印字()
}

顧客 "1" -* 口座
顧客 "1" *- "0..1" カード

口座 "1" o- 通帳
口座 "1" o- 取引履歴

@enduml